// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: extension/extension.proto

package extension

import (
	hcommon "github.com/hiddify/hiddify-core/v2/hcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionResponseType int32

const (
	ExtensionResponseType_NOTHING     ExtensionResponseType = 0
	ExtensionResponseType_UPDATE_UI   ExtensionResponseType = 1
	ExtensionResponseType_SHOW_DIALOG ExtensionResponseType = 2
	ExtensionResponseType_END         ExtensionResponseType = 3
)

// Enum value maps for ExtensionResponseType.
var (
	ExtensionResponseType_name = map[int32]string{
		0: "NOTHING",
		1: "UPDATE_UI",
		2: "SHOW_DIALOG",
		3: "END",
	}
	ExtensionResponseType_value = map[string]int32{
		"NOTHING":     0,
		"UPDATE_UI":   1,
		"SHOW_DIALOG": 2,
		"END":         3,
	}
)

func (x ExtensionResponseType) Enum() *ExtensionResponseType {
	p := new(ExtensionResponseType)
	*p = x
	return p
}

func (x ExtensionResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_extension_proto_enumTypes[0].Descriptor()
}

func (ExtensionResponseType) Type() protoreflect.EnumType {
	return &file_extension_extension_proto_enumTypes[0]
}

func (x ExtensionResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionResponseType.Descriptor instead.
func (ExtensionResponseType) EnumDescriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{0}
}

type ExtensionActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Code          hcommon.ResponseCode   `protobuf:"varint,2,opt,name=code,proto3,enum=hcommon.ResponseCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionActionResult) Reset() {
	*x = ExtensionActionResult{}
	mi := &file_extension_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionActionResult) ProtoMessage() {}

func (x *ExtensionActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionActionResult.ProtoReflect.Descriptor instead.
func (*ExtensionActionResult) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{0}
}

func (x *ExtensionActionResult) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionActionResult) GetCode() hcommon.ResponseCode {
	if x != nil {
		return x.Code
	}
	return hcommon.ResponseCode(0)
}

func (x *ExtensionActionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExtensionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extensions    []*ExtensionMsg        `protobuf:"bytes,1,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionList) Reset() {
	*x = ExtensionList{}
	mi := &file_extension_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionList) ProtoMessage() {}

func (x *ExtensionList) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionList.ProtoReflect.Descriptor instead.
func (*ExtensionList) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionList) GetExtensions() []*ExtensionMsg {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type EditExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditExtensionRequest) Reset() {
	*x = EditExtensionRequest{}
	mi := &file_extension_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditExtensionRequest) ProtoMessage() {}

func (x *EditExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditExtensionRequest.ProtoReflect.Descriptor instead.
func (*EditExtensionRequest) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{2}
}

func (x *EditExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *EditExtensionRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type ExtensionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enable        bool                   `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMsg) Reset() {
	*x = ExtensionMsg{}
	mi := &file_extension_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMsg) ProtoMessage() {}

func (x *ExtensionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMsg.ProtoReflect.Descriptor instead.
func (*ExtensionMsg) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{3}
}

func (x *ExtensionMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtensionMsg) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionMsg) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtensionMsg) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type ExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionRequest) Reset() {
	*x = ExtensionRequest{}
	mi := &file_extension_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionRequest) ProtoMessage() {}

func (x *ExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionRequest.ProtoReflect.Descriptor instead.
func (*ExtensionRequest) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendExtensionDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Button        string                 `protobuf:"bytes,2,opt,name=button,proto3" json:"button,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExtensionDataRequest) Reset() {
	*x = SendExtensionDataRequest{}
	mi := &file_extension_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExtensionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExtensionDataRequest) ProtoMessage() {}

func (x *SendExtensionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExtensionDataRequest.ProtoReflect.Descriptor instead.
func (*SendExtensionDataRequest) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{5}
}

func (x *SendExtensionDataRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *SendExtensionDataRequest) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *SendExtensionDataRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExtensionResponseType  `protobuf:"varint,1,opt,name=type,proto3,enum=extension.ExtensionResponseType" json:"type,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	JsonUi        string                 `protobuf:"bytes,3,opt,name=json_ui,json=jsonUi,proto3" json:"json_ui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionResponse) Reset() {
	*x = ExtensionResponse{}
	mi := &file_extension_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionResponse) ProtoMessage() {}

func (x *ExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionResponse.ProtoReflect.Descriptor instead.
func (*ExtensionResponse) Descriptor() ([]byte, []int) {
	return file_extension_extension_proto_rawDescGZIP(), []int{6}
}

func (x *ExtensionResponse) GetType() ExtensionResponseType {
	if x != nil {
		return x.Type
	}
	return ExtensionResponseType_NOTHING
}

func (x *ExtensionResponse) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionResponse) GetJsonUi() string {
	if x != nil {
		return x.JsonUi
	}
	return ""
}

var File_extension_extension_proto protoreflect.FileDescriptor

const file_extension_extension_proto_rawDesc = "" +
	"\n" +
	"\x19extension/extension.proto\x12\textension\x1a\x17v2/hcommon/common.proto\"\x7f\n" +
	"\x15ExtensionActionResult\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12)\n" +
	"\x04code\x18\x02 \x01(\x0e2\x15.hcommon.ResponseCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\rExtensionList\x127\n" +
	"\n" +
	"extensions\x18\x01 \x03(\v2\x17.extension.ExtensionMsgR\n" +
	"extensions\"Q\n" +
	"\x14EditExtensionRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\"n\n" +
	"\fExtensionMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06enable\x18\x04 \x01(\bR\x06enable\"\xa9\x01\n" +
	"\x10ExtensionRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x129\n" +
	"\x04data\x18\x02 \x03(\v2%.extension.ExtensionRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x18SendExtensionDataRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12\x16\n" +
	"\x06button\x18\x02 \x01(\tR\x06button\x12A\n" +
	"\x04data\x18\x03 \x03(\v2-.extension.SendExtensionDataRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x01\n" +
	"\x11ExtensionResponse\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .extension.ExtensionResponseTypeR\x04type\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12\x17\n" +
	"\ajson_ui\x18\x03 \x01(\tR\x06jsonUi*M\n" +
	"\x15ExtensionResponseType\x12\v\n" +
	"\aNOTHING\x10\x00\x12\r\n" +
	"\tUPDATE_UI\x10\x01\x12\x0f\n" +
	"\vSHOW_DIALOG\x10\x02\x12\a\n" +
	"\x03END\x10\x03BK\n" +
	"\x1ecom.hiddify.core.api.extensionZ)github.com/hiddify/hiddify-core/extensionb\x06proto3"

var (
	file_extension_extension_proto_rawDescOnce sync.Once
	file_extension_extension_proto_rawDescData []byte
)

func file_extension_extension_proto_rawDescGZIP() []byte {
	file_extension_extension_proto_rawDescOnce.Do(func() {
		file_extension_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_extension_proto_rawDesc), len(file_extension_extension_proto_rawDesc)))
	})
	return file_extension_extension_proto_rawDescData
}

var file_extension_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extension_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_extension_extension_proto_goTypes = []any{
	(ExtensionResponseType)(0),       // 0: extension.ExtensionResponseType
	(*ExtensionActionResult)(nil),    // 1: extension.ExtensionActionResult
	(*ExtensionList)(nil),            // 2: extension.ExtensionList
	(*EditExtensionRequest)(nil),     // 3: extension.EditExtensionRequest
	(*ExtensionMsg)(nil),             // 4: extension.ExtensionMsg
	(*ExtensionRequest)(nil),         // 5: extension.ExtensionRequest
	(*SendExtensionDataRequest)(nil), // 6: extension.SendExtensionDataRequest
	(*ExtensionResponse)(nil),        // 7: extension.ExtensionResponse
	nil,                              // 8: extension.ExtensionRequest.DataEntry
	nil,                              // 9: extension.SendExtensionDataRequest.DataEntry
	(hcommon.ResponseCode)(0),        // 10: hcommon.ResponseCode
}
var file_extension_extension_proto_depIdxs = []int32{
	10, // 0: extension.ExtensionActionResult.code:type_name -> hcommon.ResponseCode
	4,  // 1: extension.ExtensionList.extensions:type_name -> extension.ExtensionMsg
	8,  // 2: extension.ExtensionRequest.data:type_name -> extension.ExtensionRequest.DataEntry
	9,  // 3: extension.SendExtensionDataRequest.data:type_name -> extension.SendExtensionDataRequest.DataEntry
	0,  // 4: extension.ExtensionResponse.type:type_name -> extension.ExtensionResponseType
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_extension_extension_proto_init() }
func file_extension_extension_proto_init() {
	if File_extension_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_extension_proto_rawDesc), len(file_extension_extension_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extension_extension_proto_goTypes,
		DependencyIndexes: file_extension_extension_proto_depIdxs,
		EnumInfos:         file_extension_extension_proto_enumTypes,
		MessageInfos:      file_extension_extension_proto_msgTypes,
	}.Build()
	File_extension_extension_proto = out.File
	file_extension_extension_proto_goTypes = nil
	file_extension_extension_proto_depIdxs = nil
}
