// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: extension/extension_service.proto

package extension

import (
	hcommon "github.com/hiddify/hiddify-core/v2/hcommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_extension_extension_service_proto protoreflect.FileDescriptor

const file_extension_extension_service_proto_rawDesc = "" +
	"\n" +
	"!extension/extension_service.proto\x12\textension\x1a\x19extension/extension.proto\x1a\x17v2/hcommon/common.proto2\xdf\x03\n" +
	"\x14ExtensionHostService\x12<\n" +
	"\x0eListExtensions\x12\x0e.hcommon.Empty\x1a\x18.extension.ExtensionList\"\x00\x12H\n" +
	"\aConnect\x12\x1b.extension.ExtensionRequest\x1a\x1c.extension.ExtensionResponse\"\x000\x01\x12T\n" +
	"\rEditExtension\x12\x1f.extension.EditExtensionRequest\x1a .extension.ExtensionActionResult\"\x00\x12U\n" +
	"\n" +
	"SubmitForm\x12#.extension.SendExtensionDataRequest\x1a .extension.ExtensionActionResult\"\x00\x12H\n" +
	"\x05Close\x12\x1b.extension.ExtensionRequest\x1a .extension.ExtensionActionResult\"\x00\x12H\n" +
	"\x05GetUI\x12\x1b.extension.ExtensionRequest\x1a .extension.ExtensionActionResult\"\x00BK\n" +
	"\x1ecom.hiddify.core.api.extensionZ)github.com/hiddify/hiddify-core/extensionb\x06proto3"

var file_extension_extension_service_proto_goTypes = []any{
	(*hcommon.Empty)(nil),            // 0: hcommon.Empty
	(*ExtensionRequest)(nil),         // 1: extension.ExtensionRequest
	(*EditExtensionRequest)(nil),     // 2: extension.EditExtensionRequest
	(*SendExtensionDataRequest)(nil), // 3: extension.SendExtensionDataRequest
	(*ExtensionList)(nil),            // 4: extension.ExtensionList
	(*ExtensionResponse)(nil),        // 5: extension.ExtensionResponse
	(*ExtensionActionResult)(nil),    // 6: extension.ExtensionActionResult
}
var file_extension_extension_service_proto_depIdxs = []int32{
	0, // 0: extension.ExtensionHostService.ListExtensions:input_type -> hcommon.Empty
	1, // 1: extension.ExtensionHostService.Connect:input_type -> extension.ExtensionRequest
	2, // 2: extension.ExtensionHostService.EditExtension:input_type -> extension.EditExtensionRequest
	3, // 3: extension.ExtensionHostService.SubmitForm:input_type -> extension.SendExtensionDataRequest
	1, // 4: extension.ExtensionHostService.Close:input_type -> extension.ExtensionRequest
	1, // 5: extension.ExtensionHostService.GetUI:input_type -> extension.ExtensionRequest
	4, // 6: extension.ExtensionHostService.ListExtensions:output_type -> extension.ExtensionList
	5, // 7: extension.ExtensionHostService.Connect:output_type -> extension.ExtensionResponse
	6, // 8: extension.ExtensionHostService.EditExtension:output_type -> extension.ExtensionActionResult
	6, // 9: extension.ExtensionHostService.SubmitForm:output_type -> extension.ExtensionActionResult
	6, // 10: extension.ExtensionHostService.Close:output_type -> extension.ExtensionActionResult
	6, // 11: extension.ExtensionHostService.GetUI:output_type -> extension.ExtensionActionResult
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_extension_extension_service_proto_init() }
func file_extension_extension_service_proto_init() {
	if File_extension_extension_service_proto != nil {
		return
	}
	file_extension_extension_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_extension_service_proto_rawDesc), len(file_extension_extension_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_extension_service_proto_goTypes,
		DependencyIndexes: file_extension_extension_service_proto_depIdxs,
	}.Build()
	File_extension_extension_service_proto = out.File
	file_extension_extension_service_proto_goTypes = nil
	file_extension_extension_service_proto_depIdxs = nil
}
