// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: controlv1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_GetSnapshot_FullMethodName        = "/hiddify.control.v1.ControlService/GetSnapshot"
	ControlService_WatchEvents_FullMethodName        = "/hiddify.control.v1.ControlService/WatchEvents"
	ControlService_Connect_FullMethodName            = "/hiddify.control.v1.ControlService/Connect"
	ControlService_Disconnect_FullMethodName         = "/hiddify.control.v1.ControlService/Disconnect"
	ControlService_Restart_FullMethodName            = "/hiddify.control.v1.ControlService/Restart"
	ControlService_ListProfiles_FullMethodName       = "/hiddify.control.v1.ControlService/ListProfiles"
	ControlService_GetProfile_FullMethodName         = "/hiddify.control.v1.ControlService/GetProfile"
	ControlService_AddRemoteProfile_FullMethodName   = "/hiddify.control.v1.ControlService/AddRemoteProfile"
	ControlService_AddLocalProfile_FullMethodName    = "/hiddify.control.v1.ControlService/AddLocalProfile"
	ControlService_UpdateProfile_FullMethodName      = "/hiddify.control.v1.ControlService/UpdateProfile"
	ControlService_RefreshProfile_FullMethodName     = "/hiddify.control.v1.ControlService/RefreshProfile"
	ControlService_DeleteProfile_FullMethodName      = "/hiddify.control.v1.ControlService/DeleteProfile"
	ControlService_SetActiveProfile_FullMethodName   = "/hiddify.control.v1.ControlService/SetActiveProfile"
	ControlService_ListOutboundGroups_FullMethodName = "/hiddify.control.v1.ControlService/ListOutboundGroups"
	ControlService_SelectOutbound_FullMethodName     = "/hiddify.control.v1.ControlService/SelectOutbound"
	ControlService_TestOutbounds_FullMethodName      = "/hiddify.control.v1.ControlService/TestOutbounds"
	ControlService_TailLogs_FullMethodName           = "/hiddify.control.v1.ControlService/TailLogs"
	ControlService_ClearLogs_FullMethodName          = "/hiddify.control.v1.ControlService/ClearLogs"
	ControlService_GetSettings_FullMethodName        = "/hiddify.control.v1.ControlService/GetSettings"
	ControlService_ValidateSettings_FullMethodName   = "/hiddify.control.v1.ControlService/ValidateSettings"
	ControlService_UpdateSettings_FullMethodName     = "/hiddify.control.v1.ControlService/UpdateSettings"
	ControlService_ResetSettings_FullMethodName      = "/hiddify.control.v1.ControlService/ResetSettings"
	ControlService_ExportSettings_FullMethodName     = "/hiddify.control.v1.ControlService/ExportSettings"
	ControlService_ImportSettings_FullMethodName     = "/hiddify.control.v1.ControlService/ImportSettings"
	ControlService_GetServiceInfo_FullMethodName     = "/hiddify.control.v1.ControlService/GetServiceInfo"
	ControlService_SetAutoConnect_FullMethodName     = "/hiddify.control.v1.ControlService/SetAutoConnect"
	ControlService_GetDiagnostics_FullMethodName     = "/hiddify.control.v1.ControlService/GetDiagnostics"
	ControlService_PollAgent_FullMethodName          = "/hiddify.control.v1.ControlService/PollAgent"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlService is the versioned, local-only API between thin clients and the
// daemon. Requests describe user intent; they never expose core file paths or
// daemon storage details.
type ControlServiceClient interface {
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*OperationResult, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*OperationResult, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResult, error)
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	AddRemoteProfile(ctx context.Context, in *AddRemoteProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	AddLocalProfile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddLocalProfileRequest, Profile], error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*Profile, error)
	RefreshProfile(ctx context.Context, in *RefreshProfileRequest, opts ...grpc.CallOption) (*OperationResult, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*OperationResult, error)
	SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*OperationResult, error)
	ListOutboundGroups(ctx context.Context, in *ListOutboundGroupsRequest, opts ...grpc.CallOption) (*ListOutboundGroupsResponse, error)
	SelectOutbound(ctx context.Context, in *SelectOutboundRequest, opts ...grpc.CallOption) (*OperationResult, error)
	TestOutbounds(ctx context.Context, in *TestOutboundsRequest, opts ...grpc.CallOption) (*OperationResult, error)
	TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	ClearLogs(ctx context.Context, in *ClearLogsRequest, opts ...grpc.CallOption) (*OperationResult, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	ValidateSettings(ctx context.Context, in *ValidateSettingsRequest, opts ...grpc.CallOption) (*ValidationResult, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	ResetSettings(ctx context.Context, in *ResetSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	ExportSettings(ctx context.Context, in *ExportSettingsRequest, opts ...grpc.CallOption) (*ExportSettingsResponse, error)
	ImportSettings(ctx context.Context, in *ImportSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error)
	SetAutoConnect(ctx context.Context, in *SetAutoConnectRequest, opts ...grpc.CallOption) (*OperationResult, error)
	GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*Diagnostics, error)
	PollAgent(ctx context.Context, in *AgentPollRequest, opts ...grpc.CallOption) (*AgentInstruction, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, ControlService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *controlServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, ControlService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, ControlService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddRemoteProfile(ctx context.Context, in *AddRemoteProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, ControlService_AddRemoteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AddLocalProfile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddLocalProfileRequest, Profile], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[1], ControlService_AddLocalProfile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddLocalProfileRequest, Profile]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_AddLocalProfileClient = grpc.ClientStreamingClient[AddLocalProfileRequest, Profile]

func (c *controlServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*Profile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Profile)
	err := c.cc.Invoke(ctx, ControlService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RefreshProfile(ctx context.Context, in *RefreshProfileRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_RefreshProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetActiveProfile(ctx context.Context, in *SetActiveProfileRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_SetActiveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListOutboundGroups(ctx context.Context, in *ListOutboundGroupsRequest, opts ...grpc.CallOption) (*ListOutboundGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutboundGroupsResponse)
	err := c.cc.Invoke(ctx, ControlService_ListOutboundGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SelectOutbound(ctx context.Context, in *SelectOutboundRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_SelectOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) TestOutbounds(ctx context.Context, in *TestOutboundsRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_TestOutbounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[2], ControlService_TailLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_TailLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *controlServiceClient) ClearLogs(ctx context.Context, in *ClearLogsRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_ClearLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, ControlService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ValidateSettings(ctx context.Context, in *ValidateSettingsRequest, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, ControlService_ValidateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, ControlService_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ResetSettings(ctx context.Context, in *ResetSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, ControlService_ResetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ExportSettings(ctx context.Context, in *ExportSettingsRequest, opts ...grpc.CallOption) (*ExportSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSettingsResponse)
	err := c.cc.Invoke(ctx, ControlService_ExportSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ImportSettings(ctx context.Context, in *ImportSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, ControlService_ImportSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*ServiceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceInfo)
	err := c.cc.Invoke(ctx, ControlService_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SetAutoConnect(ctx context.Context, in *SetAutoConnectRequest, opts ...grpc.CallOption) (*OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResult)
	err := c.cc.Invoke(ctx, ControlService_SetAutoConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetDiagnostics(ctx context.Context, in *GetDiagnosticsRequest, opts ...grpc.CallOption) (*Diagnostics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Diagnostics)
	err := c.cc.Invoke(ctx, ControlService_GetDiagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) PollAgent(ctx context.Context, in *AgentPollRequest, opts ...grpc.CallOption) (*AgentInstruction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInstruction)
	err := c.cc.Invoke(ctx, ControlService_PollAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
//
// ControlService is the versioned, local-only API between thin clients and the
// daemon. Requests describe user intent; they never expose core file paths or
// daemon storage details.
type ControlServiceServer interface {
	GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error)
	WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	Connect(context.Context, *ConnectRequest) (*OperationResult, error)
	Disconnect(context.Context, *DisconnectRequest) (*OperationResult, error)
	Restart(context.Context, *RestartRequest) (*OperationResult, error)
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*Profile, error)
	AddRemoteProfile(context.Context, *AddRemoteProfileRequest) (*Profile, error)
	AddLocalProfile(grpc.ClientStreamingServer[AddLocalProfileRequest, Profile]) error
	UpdateProfile(context.Context, *UpdateProfileRequest) (*Profile, error)
	RefreshProfile(context.Context, *RefreshProfileRequest) (*OperationResult, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*OperationResult, error)
	SetActiveProfile(context.Context, *SetActiveProfileRequest) (*OperationResult, error)
	ListOutboundGroups(context.Context, *ListOutboundGroupsRequest) (*ListOutboundGroupsResponse, error)
	SelectOutbound(context.Context, *SelectOutboundRequest) (*OperationResult, error)
	TestOutbounds(context.Context, *TestOutboundsRequest) (*OperationResult, error)
	TailLogs(*TailLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	ClearLogs(context.Context, *ClearLogsRequest) (*OperationResult, error)
	GetSettings(context.Context, *GetSettingsRequest) (*Settings, error)
	ValidateSettings(context.Context, *ValidateSettingsRequest) (*ValidationResult, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*Settings, error)
	ResetSettings(context.Context, *ResetSettingsRequest) (*Settings, error)
	ExportSettings(context.Context, *ExportSettingsRequest) (*ExportSettingsResponse, error)
	ImportSettings(context.Context, *ImportSettingsRequest) (*Settings, error)
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*ServiceInfo, error)
	SetAutoConnect(context.Context, *SetAutoConnectRequest) (*OperationResult, error)
	GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*Diagnostics, error)
	PollAgent(context.Context, *AgentPollRequest) (*AgentInstruction, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*Snapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedControlServiceServer) WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedControlServiceServer) Connect(context.Context, *ConnectRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedControlServiceServer) Disconnect(context.Context, *DisconnectRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedControlServiceServer) Restart(context.Context, *RestartRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedControlServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedControlServiceServer) GetProfile(context.Context, *GetProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedControlServiceServer) AddRemoteProfile(context.Context, *AddRemoteProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRemoteProfile not implemented")
}
func (UnimplementedControlServiceServer) AddLocalProfile(grpc.ClientStreamingServer[AddLocalProfileRequest, Profile]) error {
	return status.Errorf(codes.Unimplemented, "method AddLocalProfile not implemented")
}
func (UnimplementedControlServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedControlServiceServer) RefreshProfile(context.Context, *RefreshProfileRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshProfile not implemented")
}
func (UnimplementedControlServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedControlServiceServer) SetActiveProfile(context.Context, *SetActiveProfileRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetActiveProfile not implemented")
}
func (UnimplementedControlServiceServer) ListOutboundGroups(context.Context, *ListOutboundGroupsRequest) (*ListOutboundGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOutboundGroups not implemented")
}
func (UnimplementedControlServiceServer) SelectOutbound(context.Context, *SelectOutboundRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectOutbound not implemented")
}
func (UnimplementedControlServiceServer) TestOutbounds(context.Context, *TestOutboundsRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestOutbounds not implemented")
}
func (UnimplementedControlServiceServer) TailLogs(*TailLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method TailLogs not implemented")
}
func (UnimplementedControlServiceServer) ClearLogs(context.Context, *ClearLogsRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearLogs not implemented")
}
func (UnimplementedControlServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedControlServiceServer) ValidateSettings(context.Context, *ValidateSettingsRequest) (*ValidationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSettings not implemented")
}
func (UnimplementedControlServiceServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedControlServiceServer) ResetSettings(context.Context, *ResetSettingsRequest) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetSettings not implemented")
}
func (UnimplementedControlServiceServer) ExportSettings(context.Context, *ExportSettingsRequest) (*ExportSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSettings not implemented")
}
func (UnimplementedControlServiceServer) ImportSettings(context.Context, *ImportSettingsRequest) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSettings not implemented")
}
func (UnimplementedControlServiceServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*ServiceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedControlServiceServer) SetAutoConnect(context.Context, *SetAutoConnectRequest) (*OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoConnect not implemented")
}
func (UnimplementedControlServiceServer) GetDiagnostics(context.Context, *GetDiagnosticsRequest) (*Diagnostics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnostics not implemented")
}
func (UnimplementedControlServiceServer) PollAgent(context.Context, *AgentPollRequest) (*AgentInstruction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollAgent not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _ControlService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddRemoteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRemoteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AddRemoteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AddRemoteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AddRemoteProfile(ctx, req.(*AddRemoteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AddLocalProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).AddLocalProfile(&grpc.GenericServerStream[AddLocalProfileRequest, Profile]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_AddLocalProfileServer = grpc.ClientStreamingServer[AddLocalProfileRequest, Profile]

func _ControlService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RefreshProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RefreshProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RefreshProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RefreshProfile(ctx, req.(*RefreshProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetActiveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetActiveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetActiveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetActiveProfile(ctx, req.(*SetActiveProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListOutboundGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutboundGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListOutboundGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListOutboundGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListOutboundGroups(ctx, req.(*ListOutboundGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SelectOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectOutboundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SelectOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SelectOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SelectOutbound(ctx, req.(*SelectOutboundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_TestOutbounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestOutboundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).TestOutbounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_TestOutbounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).TestOutbounds(ctx, req.(*TestOutboundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_TailLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).TailLogs(m, &grpc.GenericServerStream[TailLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_TailLogsServer = grpc.ServerStreamingServer[LogEntry]

func _ControlService_ClearLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ClearLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ClearLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ClearLogs(ctx, req.(*ClearLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ValidateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ValidateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ValidateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ValidateSettings(ctx, req.(*ValidateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ResetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ResetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ResetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ResetSettings(ctx, req.(*ResetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ExportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ExportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ExportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ExportSettings(ctx, req.(*ExportSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ImportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ImportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ImportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ImportSettings(ctx, req.(*ImportSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SetAutoConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SetAutoConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SetAutoConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SetAutoConnect(ctx, req.(*SetAutoConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetDiagnostics(ctx, req.(*GetDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_PollAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PollAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_PollAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PollAgent(ctx, req.(*AgentPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hiddify.control.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _ControlService_GetSnapshot_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _ControlService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _ControlService_Disconnect_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _ControlService_Restart_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ControlService_ListProfiles_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ControlService_GetProfile_Handler,
		},
		{
			MethodName: "AddRemoteProfile",
			Handler:    _ControlService_AddRemoteProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _ControlService_UpdateProfile_Handler,
		},
		{
			MethodName: "RefreshProfile",
			Handler:    _ControlService_RefreshProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ControlService_DeleteProfile_Handler,
		},
		{
			MethodName: "SetActiveProfile",
			Handler:    _ControlService_SetActiveProfile_Handler,
		},
		{
			MethodName: "ListOutboundGroups",
			Handler:    _ControlService_ListOutboundGroups_Handler,
		},
		{
			MethodName: "SelectOutbound",
			Handler:    _ControlService_SelectOutbound_Handler,
		},
		{
			MethodName: "TestOutbounds",
			Handler:    _ControlService_TestOutbounds_Handler,
		},
		{
			MethodName: "ClearLogs",
			Handler:    _ControlService_ClearLogs_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _ControlService_GetSettings_Handler,
		},
		{
			MethodName: "ValidateSettings",
			Handler:    _ControlService_ValidateSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _ControlService_UpdateSettings_Handler,
		},
		{
			MethodName: "ResetSettings",
			Handler:    _ControlService_ResetSettings_Handler,
		},
		{
			MethodName: "ExportSettings",
			Handler:    _ControlService_ExportSettings_Handler,
		},
		{
			MethodName: "ImportSettings",
			Handler:    _ControlService_ImportSettings_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _ControlService_GetServiceInfo_Handler,
		},
		{
			MethodName: "SetAutoConnect",
			Handler:    _ControlService_SetAutoConnect_Handler,
		},
		{
			MethodName: "GetDiagnostics",
			Handler:    _ControlService_GetDiagnostics_Handler,
		},
		{
			MethodName: "PollAgent",
			Handler:    _ControlService_PollAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _ControlService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddLocalProfile",
			Handler:       _ControlService_AddLocalProfile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TailLogs",
			Handler:       _ControlService_TailLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controlv1/control.proto",
}
