// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v2/hello/hello_service.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v2_hello_hello_service_proto protoreflect.FileDescriptor

const file_v2_hello_hello_service_proto_rawDesc = "" +
	"\n" +
	"\x1cv2/hello/hello_service.proto\x12\x05hello\x1a\x14v2/hello/hello.proto2\x7f\n" +
	"\x05Hello\x125\n" +
	"\bSayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\x12?\n" +
	"\x0eSayHelloStream\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse(\x010\x01BI\n" +
	"\x1dcom.hiddify.core.api.v2.helloZ(github.com/hiddify/hiddify-core/v2/hellob\x06proto3"

var file_v2_hello_hello_service_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: hello.HelloRequest
	(*HelloResponse)(nil), // 1: hello.HelloResponse
}
var file_v2_hello_hello_service_proto_depIdxs = []int32{
	0, // 0: hello.Hello.SayHello:input_type -> hello.HelloRequest
	0, // 1: hello.Hello.SayHelloStream:input_type -> hello.HelloRequest
	1, // 2: hello.Hello.SayHello:output_type -> hello.HelloResponse
	1, // 3: hello.Hello.SayHelloStream:output_type -> hello.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_hello_hello_service_proto_init() }
func file_v2_hello_hello_service_proto_init() {
	if File_v2_hello_hello_service_proto != nil {
		return
	}
	file_v2_hello_hello_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_hello_hello_service_proto_rawDesc), len(file_v2_hello_hello_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_hello_hello_service_proto_goTypes,
		DependencyIndexes: file_v2_hello_hello_service_proto_depIdxs,
	}.Build()
	File_v2_hello_hello_service_proto = out.File
	file_v2_hello_hello_service_proto_goTypes = nil
	file_v2_hello_hello_service_proto_depIdxs = nil
}
