// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hiddifyrpc/hiddify.proto

package hiddifyrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_OK     ResponseCode = 0
	ResponseCode_FAILED ResponseCode = 1
)

var ResponseCode_name = map[int32]string{
	0: "OK",
	1: "FAILED",
}

var ResponseCode_value = map[string]int32{
	"OK":     0,
	"FAILED": 1,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{0}
}

type CoreState int32

const (
	CoreState_STOPPED  CoreState = 0
	CoreState_STARTING CoreState = 1
	CoreState_STARTED  CoreState = 2
	CoreState_STOPPING CoreState = 3
)

var CoreState_name = map[int32]string{
	0: "STOPPED",
	1: "STARTING",
	2: "STARTED",
	3: "STOPPING",
}

var CoreState_value = map[string]int32{
	"STOPPED":  0,
	"STARTING": 1,
	"STARTED":  2,
	"STOPPING": 3,
}

func (x CoreState) String() string {
	return proto.EnumName(CoreState_name, int32(x))
}

func (CoreState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{1}
}

type MessageType int32

const (
	MessageType_EMPTY                 MessageType = 0
	MessageType_EMPTY_CONFIGURATION   MessageType = 1
	MessageType_START_COMMAND_SERVER  MessageType = 2
	MessageType_CREATE_SERVICE        MessageType = 3
	MessageType_START_SERVICE         MessageType = 4
	MessageType_UNEXPECTED_ERROR      MessageType = 5
	MessageType_ALREADY_STARTED       MessageType = 6
	MessageType_ALREADY_STOPPED       MessageType = 7
	MessageType_INSTANCE_NOT_FOUND    MessageType = 8
	MessageType_INSTANCE_NOT_STOPPED  MessageType = 9
	MessageType_INSTANCE_NOT_STARTED  MessageType = 10
	MessageType_ERROR_BUILDING_CONFIG MessageType = 11
	MessageType_ERROR_PARSING_CONFIG  MessageType = 12
	MessageType_ERROR_READING_CONFIG  MessageType = 13
)

var MessageType_name = map[int32]string{
	0:  "EMPTY",
	1:  "EMPTY_CONFIGURATION",
	2:  "START_COMMAND_SERVER",
	3:  "CREATE_SERVICE",
	4:  "START_SERVICE",
	5:  "UNEXPECTED_ERROR",
	6:  "ALREADY_STARTED",
	7:  "ALREADY_STOPPED",
	8:  "INSTANCE_NOT_FOUND",
	9:  "INSTANCE_NOT_STOPPED",
	10: "INSTANCE_NOT_STARTED",
	11: "ERROR_BUILDING_CONFIG",
	12: "ERROR_PARSING_CONFIG",
	13: "ERROR_READING_CONFIG",
}

var MessageType_value = map[string]int32{
	"EMPTY":                 0,
	"EMPTY_CONFIGURATION":   1,
	"START_COMMAND_SERVER":  2,
	"CREATE_SERVICE":        3,
	"START_SERVICE":         4,
	"UNEXPECTED_ERROR":      5,
	"ALREADY_STARTED":       6,
	"ALREADY_STOPPED":       7,
	"INSTANCE_NOT_FOUND":    8,
	"INSTANCE_NOT_STOPPED":  9,
	"INSTANCE_NOT_STARTED":  10,
	"ERROR_BUILDING_CONFIG": 11,
	"ERROR_PARSING_CONFIG":  12,
	"ERROR_READING_CONFIG":  13,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{2}
}

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
	LogLevel_FATAL   LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
	4: "FATAL",
}

var LogLevel_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
	"FATAL":   4,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{3}
}

type LogType int32

const (
	LogType_CORE    LogType = 0
	LogType_SERVICE LogType = 1
	LogType_CONFIG  LogType = 2
)

var LogType_name = map[int32]string{
	0: "CORE",
	1: "SERVICE",
	2: "CONFIG",
}

var LogType_value = map[string]int32{
	"CORE":    0,
	"SERVICE": 1,
	"CONFIG":  2,
}

func (x LogType) String() string {
	return proto.EnumName(LogType_name, int32(x))
}

func (LogType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{4}
}

type CoreInfoResponse struct {
	CoreState            CoreState   `protobuf:"varint,1,opt,name=core_state,json=coreState,proto3,enum=hiddifyrpc.CoreState" json:"core_state,omitempty"`
	MessageType          MessageType `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=hiddifyrpc.MessageType" json:"message_type,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CoreInfoResponse) Reset()         { *m = CoreInfoResponse{} }
func (m *CoreInfoResponse) String() string { return proto.CompactTextString(m) }
func (*CoreInfoResponse) ProtoMessage()    {}
func (*CoreInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{0}
}

func (m *CoreInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoreInfoResponse.Unmarshal(m, b)
}
func (m *CoreInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoreInfoResponse.Marshal(b, m, deterministic)
}
func (m *CoreInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoreInfoResponse.Merge(m, src)
}
func (m *CoreInfoResponse) XXX_Size() int {
	return xxx_messageInfo_CoreInfoResponse.Size(m)
}
func (m *CoreInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoreInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoreInfoResponse proto.InternalMessageInfo

func (m *CoreInfoResponse) GetCoreState() CoreState {
	if m != nil {
		return m.CoreState
	}
	return CoreState_STOPPED
}

func (m *CoreInfoResponse) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_EMPTY
}

func (m *CoreInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StartRequest struct {
	ConfigPath             string   `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigContent          string   `protobuf:"bytes,2,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	DisableMemoryLimit     bool     `protobuf:"varint,3,opt,name=disable_memory_limit,json=disableMemoryLimit,proto3" json:"disable_memory_limit,omitempty"`
	DelayStart             bool     `protobuf:"varint,4,opt,name=delay_start,json=delayStart,proto3" json:"delay_start,omitempty"`
	EnableOldCommandServer bool     `protobuf:"varint,5,opt,name=enable_old_command_server,json=enableOldCommandServer,proto3" json:"enable_old_command_server,omitempty"`
	EnableRawConfig        bool     `protobuf:"varint,6,opt,name=enable_raw_config,json=enableRawConfig,proto3" json:"enable_raw_config,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{1}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *StartRequest) GetConfigContent() string {
	if m != nil {
		return m.ConfigContent
	}
	return ""
}

func (m *StartRequest) GetDisableMemoryLimit() bool {
	if m != nil {
		return m.DisableMemoryLimit
	}
	return false
}

func (m *StartRequest) GetDelayStart() bool {
	if m != nil {
		return m.DelayStart
	}
	return false
}

func (m *StartRequest) GetEnableOldCommandServer() bool {
	if m != nil {
		return m.EnableOldCommandServer
	}
	return false
}

func (m *StartRequest) GetEnableRawConfig() bool {
	if m != nil {
		return m.EnableRawConfig
	}
	return false
}

type SetupRequest struct {
	BasePath             string   `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	WorkingPath          string   `protobuf:"bytes,2,opt,name=working_path,json=workingPath,proto3" json:"working_path,omitempty"`
	TempPath             string   `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetupRequest) Reset()         { *m = SetupRequest{} }
func (m *SetupRequest) String() string { return proto.CompactTextString(m) }
func (*SetupRequest) ProtoMessage()    {}
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{2}
}

func (m *SetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupRequest.Unmarshal(m, b)
}
func (m *SetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupRequest.Marshal(b, m, deterministic)
}
func (m *SetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupRequest.Merge(m, src)
}
func (m *SetupRequest) XXX_Size() int {
	return xxx_messageInfo_SetupRequest.Size(m)
}
func (m *SetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupRequest proto.InternalMessageInfo

func (m *SetupRequest) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *SetupRequest) GetWorkingPath() string {
	if m != nil {
		return m.WorkingPath
	}
	return ""
}

func (m *SetupRequest) GetTempPath() string {
	if m != nil {
		return m.TempPath
	}
	return ""
}

type Response struct {
	ResponseCode         ResponseCode `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=hiddifyrpc.ResponseCode" json:"response_code,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponseCode() ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return ResponseCode_OK
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{4}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{5}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SystemInfo struct {
	Memory               int64    `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Goroutines           int32    `protobuf:"varint,2,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	ConnectionsIn        int32    `protobuf:"varint,3,opt,name=connections_in,json=connectionsIn,proto3" json:"connections_in,omitempty"`
	ConnectionsOut       int32    `protobuf:"varint,4,opt,name=connections_out,json=connectionsOut,proto3" json:"connections_out,omitempty"`
	TrafficAvailable     bool     `protobuf:"varint,5,opt,name=traffic_available,json=trafficAvailable,proto3" json:"traffic_available,omitempty"`
	Uplink               int64    `protobuf:"varint,6,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink             int64    `protobuf:"varint,7,opt,name=downlink,proto3" json:"downlink,omitempty"`
	UplinkTotal          int64    `protobuf:"varint,8,opt,name=uplink_total,json=uplinkTotal,proto3" json:"uplink_total,omitempty"`
	DownlinkTotal        int64    `protobuf:"varint,9,opt,name=downlink_total,json=downlinkTotal,proto3" json:"downlink_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{7}
}

func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

func (m *SystemInfo) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *SystemInfo) GetGoroutines() int32 {
	if m != nil {
		return m.Goroutines
	}
	return 0
}

func (m *SystemInfo) GetConnectionsIn() int32 {
	if m != nil {
		return m.ConnectionsIn
	}
	return 0
}

func (m *SystemInfo) GetConnectionsOut() int32 {
	if m != nil {
		return m.ConnectionsOut
	}
	return 0
}

func (m *SystemInfo) GetTrafficAvailable() bool {
	if m != nil {
		return m.TrafficAvailable
	}
	return false
}

func (m *SystemInfo) GetUplink() int64 {
	if m != nil {
		return m.Uplink
	}
	return 0
}

func (m *SystemInfo) GetDownlink() int64 {
	if m != nil {
		return m.Downlink
	}
	return 0
}

func (m *SystemInfo) GetUplinkTotal() int64 {
	if m != nil {
		return m.UplinkTotal
	}
	return 0
}

func (m *SystemInfo) GetDownlinkTotal() int64 {
	if m != nil {
		return m.DownlinkTotal
	}
	return 0
}

type OutboundGroupItem struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UrlTestTime          int64    `protobuf:"varint,3,opt,name=url_test_time,json=urlTestTime,proto3" json:"url_test_time,omitempty"`
	UrlTestDelay         int32    `protobuf:"varint,4,opt,name=url_test_delay,json=urlTestDelay,proto3" json:"url_test_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutboundGroupItem) Reset()         { *m = OutboundGroupItem{} }
func (m *OutboundGroupItem) String() string { return proto.CompactTextString(m) }
func (*OutboundGroupItem) ProtoMessage()    {}
func (*OutboundGroupItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{8}
}

func (m *OutboundGroupItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboundGroupItem.Unmarshal(m, b)
}
func (m *OutboundGroupItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboundGroupItem.Marshal(b, m, deterministic)
}
func (m *OutboundGroupItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboundGroupItem.Merge(m, src)
}
func (m *OutboundGroupItem) XXX_Size() int {
	return xxx_messageInfo_OutboundGroupItem.Size(m)
}
func (m *OutboundGroupItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboundGroupItem.DiscardUnknown(m)
}

var xxx_messageInfo_OutboundGroupItem proto.InternalMessageInfo

func (m *OutboundGroupItem) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *OutboundGroupItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OutboundGroupItem) GetUrlTestTime() int64 {
	if m != nil {
		return m.UrlTestTime
	}
	return 0
}

func (m *OutboundGroupItem) GetUrlTestDelay() int32 {
	if m != nil {
		return m.UrlTestDelay
	}
	return 0
}

type OutboundGroup struct {
	Tag                  string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Selected             string               `protobuf:"bytes,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Items                []*OutboundGroupItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OutboundGroup) Reset()         { *m = OutboundGroup{} }
func (m *OutboundGroup) String() string { return proto.CompactTextString(m) }
func (*OutboundGroup) ProtoMessage()    {}
func (*OutboundGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{9}
}

func (m *OutboundGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboundGroup.Unmarshal(m, b)
}
func (m *OutboundGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboundGroup.Marshal(b, m, deterministic)
}
func (m *OutboundGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboundGroup.Merge(m, src)
}
func (m *OutboundGroup) XXX_Size() int {
	return xxx_messageInfo_OutboundGroup.Size(m)
}
func (m *OutboundGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboundGroup.DiscardUnknown(m)
}

var xxx_messageInfo_OutboundGroup proto.InternalMessageInfo

func (m *OutboundGroup) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *OutboundGroup) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OutboundGroup) GetSelected() string {
	if m != nil {
		return m.Selected
	}
	return ""
}

func (m *OutboundGroup) GetItems() []*OutboundGroupItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type OutboundGroupList struct {
	Items                []*OutboundGroup `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OutboundGroupList) Reset()         { *m = OutboundGroupList{} }
func (m *OutboundGroupList) String() string { return proto.CompactTextString(m) }
func (*OutboundGroupList) ProtoMessage()    {}
func (*OutboundGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{10}
}

func (m *OutboundGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboundGroupList.Unmarshal(m, b)
}
func (m *OutboundGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboundGroupList.Marshal(b, m, deterministic)
}
func (m *OutboundGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboundGroupList.Merge(m, src)
}
func (m *OutboundGroupList) XXX_Size() int {
	return xxx_messageInfo_OutboundGroupList.Size(m)
}
func (m *OutboundGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboundGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_OutboundGroupList proto.InternalMessageInfo

func (m *OutboundGroupList) GetItems() []*OutboundGroup {
	if m != nil {
		return m.Items
	}
	return nil
}

type WarpAccount struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarpAccount) Reset()         { *m = WarpAccount{} }
func (m *WarpAccount) String() string { return proto.CompactTextString(m) }
func (*WarpAccount) ProtoMessage()    {}
func (*WarpAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{11}
}

func (m *WarpAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarpAccount.Unmarshal(m, b)
}
func (m *WarpAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarpAccount.Marshal(b, m, deterministic)
}
func (m *WarpAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarpAccount.Merge(m, src)
}
func (m *WarpAccount) XXX_Size() int {
	return xxx_messageInfo_WarpAccount.Size(m)
}
func (m *WarpAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_WarpAccount.DiscardUnknown(m)
}

var xxx_messageInfo_WarpAccount proto.InternalMessageInfo

func (m *WarpAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *WarpAccount) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type WarpWireguardConfig struct {
	PrivateKey           string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	LocalAddressIpv4     string   `protobuf:"bytes,2,opt,name=local_address_ipv4,json=localAddressIpv4,proto3" json:"local_address_ipv4,omitempty"`
	LocalAddressIpv6     string   `protobuf:"bytes,3,opt,name=local_address_ipv6,json=localAddressIpv6,proto3" json:"local_address_ipv6,omitempty"`
	PeerPublicKey        string   `protobuf:"bytes,4,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	ClientId             string   `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarpWireguardConfig) Reset()         { *m = WarpWireguardConfig{} }
func (m *WarpWireguardConfig) String() string { return proto.CompactTextString(m) }
func (*WarpWireguardConfig) ProtoMessage()    {}
func (*WarpWireguardConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{12}
}

func (m *WarpWireguardConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarpWireguardConfig.Unmarshal(m, b)
}
func (m *WarpWireguardConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarpWireguardConfig.Marshal(b, m, deterministic)
}
func (m *WarpWireguardConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarpWireguardConfig.Merge(m, src)
}
func (m *WarpWireguardConfig) XXX_Size() int {
	return xxx_messageInfo_WarpWireguardConfig.Size(m)
}
func (m *WarpWireguardConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WarpWireguardConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WarpWireguardConfig proto.InternalMessageInfo

func (m *WarpWireguardConfig) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *WarpWireguardConfig) GetLocalAddressIpv4() string {
	if m != nil {
		return m.LocalAddressIpv4
	}
	return ""
}

func (m *WarpWireguardConfig) GetLocalAddressIpv6() string {
	if m != nil {
		return m.LocalAddressIpv6
	}
	return ""
}

func (m *WarpWireguardConfig) GetPeerPublicKey() string {
	if m != nil {
		return m.PeerPublicKey
	}
	return ""
}

func (m *WarpWireguardConfig) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type WarpGenerationResponse struct {
	Account              *WarpAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Log                  string               `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Config               *WarpWireguardConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WarpGenerationResponse) Reset()         { *m = WarpGenerationResponse{} }
func (m *WarpGenerationResponse) String() string { return proto.CompactTextString(m) }
func (*WarpGenerationResponse) ProtoMessage()    {}
func (*WarpGenerationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{13}
}

func (m *WarpGenerationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarpGenerationResponse.Unmarshal(m, b)
}
func (m *WarpGenerationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarpGenerationResponse.Marshal(b, m, deterministic)
}
func (m *WarpGenerationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarpGenerationResponse.Merge(m, src)
}
func (m *WarpGenerationResponse) XXX_Size() int {
	return xxx_messageInfo_WarpGenerationResponse.Size(m)
}
func (m *WarpGenerationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WarpGenerationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WarpGenerationResponse proto.InternalMessageInfo

func (m *WarpGenerationResponse) GetAccount() *WarpAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *WarpGenerationResponse) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *WarpGenerationResponse) GetConfig() *WarpWireguardConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SystemProxyStatus struct {
	Available            bool     `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemProxyStatus) Reset()         { *m = SystemProxyStatus{} }
func (m *SystemProxyStatus) String() string { return proto.CompactTextString(m) }
func (*SystemProxyStatus) ProtoMessage()    {}
func (*SystemProxyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{14}
}

func (m *SystemProxyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemProxyStatus.Unmarshal(m, b)
}
func (m *SystemProxyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemProxyStatus.Marshal(b, m, deterministic)
}
func (m *SystemProxyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemProxyStatus.Merge(m, src)
}
func (m *SystemProxyStatus) XXX_Size() int {
	return xxx_messageInfo_SystemProxyStatus.Size(m)
}
func (m *SystemProxyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemProxyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SystemProxyStatus proto.InternalMessageInfo

func (m *SystemProxyStatus) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *SystemProxyStatus) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ParseRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ConfigPath           string   `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	TempPath             string   `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug                bool     `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{15}
}

func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (m *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(m, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ParseRequest) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *ParseRequest) GetTempPath() string {
	if m != nil {
		return m.TempPath
	}
	return ""
}

func (m *ParseRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type ParseResponse struct {
	ResponseCode         ResponseCode `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=hiddifyrpc.ResponseCode" json:"response_code,omitempty"`
	Content              string       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message              string       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ParseResponse) Reset()         { *m = ParseResponse{} }
func (m *ParseResponse) String() string { return proto.CompactTextString(m) }
func (*ParseResponse) ProtoMessage()    {}
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{16}
}

func (m *ParseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResponse.Unmarshal(m, b)
}
func (m *ParseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResponse.Marshal(b, m, deterministic)
}
func (m *ParseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResponse.Merge(m, src)
}
func (m *ParseResponse) XXX_Size() int {
	return xxx_messageInfo_ParseResponse.Size(m)
}
func (m *ParseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResponse proto.InternalMessageInfo

func (m *ParseResponse) GetResponseCode() ResponseCode {
	if m != nil {
		return m.ResponseCode
	}
	return ResponseCode_OK
}

func (m *ParseResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ParseResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeConfigOptionsRequest struct {
	ConfigOptionsJson    string   `protobuf:"bytes,1,opt,name=config_options_json,json=configOptionsJson,proto3" json:"config_options_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeConfigOptionsRequest) Reset()         { *m = ChangeConfigOptionsRequest{} }
func (m *ChangeConfigOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeConfigOptionsRequest) ProtoMessage()    {}
func (*ChangeConfigOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{17}
}

func (m *ChangeConfigOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeConfigOptionsRequest.Unmarshal(m, b)
}
func (m *ChangeConfigOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeConfigOptionsRequest.Marshal(b, m, deterministic)
}
func (m *ChangeConfigOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeConfigOptionsRequest.Merge(m, src)
}
func (m *ChangeConfigOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeConfigOptionsRequest.Size(m)
}
func (m *ChangeConfigOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeConfigOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeConfigOptionsRequest proto.InternalMessageInfo

func (m *ChangeConfigOptionsRequest) GetConfigOptionsJson() string {
	if m != nil {
		return m.ConfigOptionsJson
	}
	return ""
}

type GenerateConfigRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TempPath             string   `protobuf:"bytes,2,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug                bool     `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateConfigRequest) Reset()         { *m = GenerateConfigRequest{} }
func (m *GenerateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateConfigRequest) ProtoMessage()    {}
func (*GenerateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{18}
}

func (m *GenerateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateConfigRequest.Unmarshal(m, b)
}
func (m *GenerateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateConfigRequest.Marshal(b, m, deterministic)
}
func (m *GenerateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateConfigRequest.Merge(m, src)
}
func (m *GenerateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateConfigRequest.Size(m)
}
func (m *GenerateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateConfigRequest proto.InternalMessageInfo

func (m *GenerateConfigRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GenerateConfigRequest) GetTempPath() string {
	if m != nil {
		return m.TempPath
	}
	return ""
}

func (m *GenerateConfigRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type GenerateConfigResponse struct {
	ConfigContent        string   `protobuf:"bytes,1,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateConfigResponse) Reset()         { *m = GenerateConfigResponse{} }
func (m *GenerateConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateConfigResponse) ProtoMessage()    {}
func (*GenerateConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{19}
}

func (m *GenerateConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateConfigResponse.Unmarshal(m, b)
}
func (m *GenerateConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateConfigResponse.Marshal(b, m, deterministic)
}
func (m *GenerateConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateConfigResponse.Merge(m, src)
}
func (m *GenerateConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateConfigResponse.Size(m)
}
func (m *GenerateConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateConfigResponse proto.InternalMessageInfo

func (m *GenerateConfigResponse) GetConfigContent() string {
	if m != nil {
		return m.ConfigContent
	}
	return ""
}

type SelectOutboundRequest struct {
	GroupTag             string   `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	OutboundTag          string   `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectOutboundRequest) Reset()         { *m = SelectOutboundRequest{} }
func (m *SelectOutboundRequest) String() string { return proto.CompactTextString(m) }
func (*SelectOutboundRequest) ProtoMessage()    {}
func (*SelectOutboundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{20}
}

func (m *SelectOutboundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectOutboundRequest.Unmarshal(m, b)
}
func (m *SelectOutboundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectOutboundRequest.Marshal(b, m, deterministic)
}
func (m *SelectOutboundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectOutboundRequest.Merge(m, src)
}
func (m *SelectOutboundRequest) XXX_Size() int {
	return xxx_messageInfo_SelectOutboundRequest.Size(m)
}
func (m *SelectOutboundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectOutboundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectOutboundRequest proto.InternalMessageInfo

func (m *SelectOutboundRequest) GetGroupTag() string {
	if m != nil {
		return m.GroupTag
	}
	return ""
}

func (m *SelectOutboundRequest) GetOutboundTag() string {
	if m != nil {
		return m.OutboundTag
	}
	return ""
}

type UrlTestRequest struct {
	GroupTag             string   `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UrlTestRequest) Reset()         { *m = UrlTestRequest{} }
func (m *UrlTestRequest) String() string { return proto.CompactTextString(m) }
func (*UrlTestRequest) ProtoMessage()    {}
func (*UrlTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{21}
}

func (m *UrlTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlTestRequest.Unmarshal(m, b)
}
func (m *UrlTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlTestRequest.Marshal(b, m, deterministic)
}
func (m *UrlTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlTestRequest.Merge(m, src)
}
func (m *UrlTestRequest) XXX_Size() int {
	return xxx_messageInfo_UrlTestRequest.Size(m)
}
func (m *UrlTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UrlTestRequest proto.InternalMessageInfo

func (m *UrlTestRequest) GetGroupTag() string {
	if m != nil {
		return m.GroupTag
	}
	return ""
}

type GenerateWarpConfigRequest struct {
	LicenseKey           string   `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateWarpConfigRequest) Reset()         { *m = GenerateWarpConfigRequest{} }
func (m *GenerateWarpConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateWarpConfigRequest) ProtoMessage()    {}
func (*GenerateWarpConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{22}
}

func (m *GenerateWarpConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateWarpConfigRequest.Unmarshal(m, b)
}
func (m *GenerateWarpConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateWarpConfigRequest.Marshal(b, m, deterministic)
}
func (m *GenerateWarpConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateWarpConfigRequest.Merge(m, src)
}
func (m *GenerateWarpConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateWarpConfigRequest.Size(m)
}
func (m *GenerateWarpConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateWarpConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateWarpConfigRequest proto.InternalMessageInfo

func (m *GenerateWarpConfigRequest) GetLicenseKey() string {
	if m != nil {
		return m.LicenseKey
	}
	return ""
}

func (m *GenerateWarpConfigRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *GenerateWarpConfigRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type SetSystemProxyEnabledRequest struct {
	IsEnabled            bool     `protobuf:"varint,1,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSystemProxyEnabledRequest) Reset()         { *m = SetSystemProxyEnabledRequest{} }
func (m *SetSystemProxyEnabledRequest) String() string { return proto.CompactTextString(m) }
func (*SetSystemProxyEnabledRequest) ProtoMessage()    {}
func (*SetSystemProxyEnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{23}
}

func (m *SetSystemProxyEnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSystemProxyEnabledRequest.Unmarshal(m, b)
}
func (m *SetSystemProxyEnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSystemProxyEnabledRequest.Marshal(b, m, deterministic)
}
func (m *SetSystemProxyEnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSystemProxyEnabledRequest.Merge(m, src)
}
func (m *SetSystemProxyEnabledRequest) XXX_Size() int {
	return xxx_messageInfo_SetSystemProxyEnabledRequest.Size(m)
}
func (m *SetSystemProxyEnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSystemProxyEnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSystemProxyEnabledRequest proto.InternalMessageInfo

func (m *SetSystemProxyEnabledRequest) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

type LogMessage struct {
	Level                LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=hiddifyrpc.LogLevel" json:"level,omitempty"`
	Type                 LogType  `protobuf:"varint,2,opt,name=type,proto3,enum=hiddifyrpc.LogType" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{24}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_DEBUG
}

func (m *LogMessage) GetType() LogType {
	if m != nil {
		return m.Type
	}
	return LogType_CORE
}

func (m *LogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{25}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

type TunnelStartRequest struct {
	Ipv6                   bool     `protobuf:"varint,1,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	ServerPort             int32    `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	StrictRoute            bool     `protobuf:"varint,3,opt,name=strict_route,json=strictRoute,proto3" json:"strict_route,omitempty"`
	EndpointIndependentNat bool     `protobuf:"varint,4,opt,name=endpoint_independent_nat,json=endpointIndependentNat,proto3" json:"endpoint_independent_nat,omitempty"`
	Stack                  string   `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TunnelStartRequest) Reset()         { *m = TunnelStartRequest{} }
func (m *TunnelStartRequest) String() string { return proto.CompactTextString(m) }
func (*TunnelStartRequest) ProtoMessage()    {}
func (*TunnelStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{26}
}

func (m *TunnelStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelStartRequest.Unmarshal(m, b)
}
func (m *TunnelStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelStartRequest.Marshal(b, m, deterministic)
}
func (m *TunnelStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelStartRequest.Merge(m, src)
}
func (m *TunnelStartRequest) XXX_Size() int {
	return xxx_messageInfo_TunnelStartRequest.Size(m)
}
func (m *TunnelStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelStartRequest proto.InternalMessageInfo

func (m *TunnelStartRequest) GetIpv6() bool {
	if m != nil {
		return m.Ipv6
	}
	return false
}

func (m *TunnelStartRequest) GetServerPort() int32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *TunnelStartRequest) GetStrictRoute() bool {
	if m != nil {
		return m.StrictRoute
	}
	return false
}

func (m *TunnelStartRequest) GetEndpointIndependentNat() bool {
	if m != nil {
		return m.EndpointIndependentNat
	}
	return false
}

func (m *TunnelStartRequest) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

type TunnelResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelResponse) Reset()         { *m = TunnelResponse{} }
func (m *TunnelResponse) String() string { return proto.CompactTextString(m) }
func (*TunnelResponse) ProtoMessage()    {}
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52c484803f63ee3, []int{27}
}

func (m *TunnelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelResponse.Unmarshal(m, b)
}
func (m *TunnelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelResponse.Marshal(b, m, deterministic)
}
func (m *TunnelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelResponse.Merge(m, src)
}
func (m *TunnelResponse) XXX_Size() int {
	return xxx_messageInfo_TunnelResponse.Size(m)
}
func (m *TunnelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelResponse proto.InternalMessageInfo

func (m *TunnelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("hiddifyrpc.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterEnum("hiddifyrpc.CoreState", CoreState_name, CoreState_value)
	proto.RegisterEnum("hiddifyrpc.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("hiddifyrpc.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterEnum("hiddifyrpc.LogType", LogType_name, LogType_value)
	proto.RegisterType((*CoreInfoResponse)(nil), "hiddifyrpc.CoreInfoResponse")
	proto.RegisterType((*StartRequest)(nil), "hiddifyrpc.StartRequest")
	proto.RegisterType((*SetupRequest)(nil), "hiddifyrpc.SetupRequest")
	proto.RegisterType((*Response)(nil), "hiddifyrpc.Response")
	proto.RegisterType((*HelloRequest)(nil), "hiddifyrpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "hiddifyrpc.HelloResponse")
	proto.RegisterType((*Empty)(nil), "hiddifyrpc.Empty")
	proto.RegisterType((*SystemInfo)(nil), "hiddifyrpc.SystemInfo")
	proto.RegisterType((*OutboundGroupItem)(nil), "hiddifyrpc.OutboundGroupItem")
	proto.RegisterType((*OutboundGroup)(nil), "hiddifyrpc.OutboundGroup")
	proto.RegisterType((*OutboundGroupList)(nil), "hiddifyrpc.OutboundGroupList")
	proto.RegisterType((*WarpAccount)(nil), "hiddifyrpc.WarpAccount")
	proto.RegisterType((*WarpWireguardConfig)(nil), "hiddifyrpc.WarpWireguardConfig")
	proto.RegisterType((*WarpGenerationResponse)(nil), "hiddifyrpc.WarpGenerationResponse")
	proto.RegisterType((*SystemProxyStatus)(nil), "hiddifyrpc.SystemProxyStatus")
	proto.RegisterType((*ParseRequest)(nil), "hiddifyrpc.ParseRequest")
	proto.RegisterType((*ParseResponse)(nil), "hiddifyrpc.ParseResponse")
	proto.RegisterType((*ChangeConfigOptionsRequest)(nil), "hiddifyrpc.ChangeConfigOptionsRequest")
	proto.RegisterType((*GenerateConfigRequest)(nil), "hiddifyrpc.GenerateConfigRequest")
	proto.RegisterType((*GenerateConfigResponse)(nil), "hiddifyrpc.GenerateConfigResponse")
	proto.RegisterType((*SelectOutboundRequest)(nil), "hiddifyrpc.SelectOutboundRequest")
	proto.RegisterType((*UrlTestRequest)(nil), "hiddifyrpc.UrlTestRequest")
	proto.RegisterType((*GenerateWarpConfigRequest)(nil), "hiddifyrpc.GenerateWarpConfigRequest")
	proto.RegisterType((*SetSystemProxyEnabledRequest)(nil), "hiddifyrpc.SetSystemProxyEnabledRequest")
	proto.RegisterType((*LogMessage)(nil), "hiddifyrpc.LogMessage")
	proto.RegisterType((*StopRequest)(nil), "hiddifyrpc.StopRequest")
	proto.RegisterType((*TunnelStartRequest)(nil), "hiddifyrpc.TunnelStartRequest")
	proto.RegisterType((*TunnelResponse)(nil), "hiddifyrpc.TunnelResponse")
}

func init() { proto.RegisterFile("hiddifyrpc/hiddify.proto", fileDescriptor_b52c484803f63ee3) }

var fileDescriptor_b52c484803f63ee3 = []byte{
	// 2025 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5b, 0x6f, 0xe3, 0xc6,
	0x15, 0x36, 0x75, 0xb1, 0xa4, 0x23, 0xc9, 0x4b, 0x8f, 0xbd, 0x8e, 0xac, 0xdd, 0xcd, 0x6e, 0x88,
	0x26, 0x71, 0xdd, 0xd4, 0x9b, 0x3a, 0xdb, 0x6c, 0x6f, 0xc1, 0x42, 0x96, 0x68, 0x47, 0x5d, 0x59,
	0x12, 0x28, 0xba, 0xdb, 0xb4, 0x40, 0x09, 0x9a, 0x1c, 0x6b, 0x59, 0x53, 0x1c, 0x96, 0x1c, 0x79,
	0x23, 0xb4, 0xe8, 0x43, 0x0b, 0xf4, 0xb9, 0x40, 0x81, 0x3e, 0xf6, 0x97, 0x14, 0xe8, 0x2f, 0xe8,
	0x73, 0xdf, 0xfb, 0x37, 0xfa, 0x52, 0xcc, 0x85, 0x12, 0x29, 0x4b, 0xeb, 0x34, 0xcd, 0xdb, 0xcc,
	0xb9, 0xf1, 0xcc, 0x99, 0x33, 0xdf, 0x7c, 0x43, 0x68, 0xbc, 0xf6, 0x5c, 0xd7, 0xbb, 0x9a, 0x45,
	0xa1, 0xf3, 0x54, 0x0e, 0x8f, 0xc2, 0x88, 0x50, 0x82, 0x60, 0xa1, 0xd1, 0xfe, 0xa6, 0x80, 0xda,
	0x26, 0x11, 0xee, 0x06, 0x57, 0xc4, 0xc0, 0x71, 0x48, 0x82, 0x18, 0xa3, 0x67, 0x00, 0x0e, 0x89,
	0xb0, 0x15, 0x53, 0x9b, 0xe2, 0x86, 0xf2, 0x44, 0x39, 0xd8, 0x3a, 0xbe, 0x7f, 0xb4, 0xf0, 0x3a,
	0x62, 0x1e, 0x23, 0xa6, 0x34, 0x2a, 0x4e, 0x32, 0x44, 0x3f, 0x82, 0xda, 0x04, 0xc7, 0xb1, 0x3d,
	0xc6, 0x16, 0x9d, 0x85, 0xb8, 0x91, 0xe3, 0x7e, 0xef, 0xa4, 0xfd, 0xce, 0x85, 0xde, 0x9c, 0x85,
	0xd8, 0xa8, 0x4e, 0x16, 0x13, 0xd4, 0x80, 0x92, 0x9c, 0x36, 0xf2, 0x4f, 0x94, 0x83, 0x8a, 0x91,
	0x4c, 0xb5, 0x3f, 0xe7, 0xa0, 0x36, 0xa2, 0x76, 0x44, 0x0d, 0xfc, 0x9b, 0x29, 0x8e, 0x29, 0x7a,
	0x0c, 0x55, 0x87, 0x04, 0x57, 0xde, 0xd8, 0x0a, 0x6d, 0xfa, 0x9a, 0x67, 0x57, 0x31, 0x40, 0x88,
	0x86, 0x36, 0x7d, 0x8d, 0xde, 0x87, 0x2d, 0x69, 0xe0, 0x90, 0x80, 0xe2, 0x80, 0xf2, 0x4c, 0x2a,
	0x46, 0x5d, 0x48, 0xdb, 0x42, 0x88, 0x3e, 0x86, 0x5d, 0xd7, 0x8b, 0xed, 0x4b, 0x1f, 0x5b, 0x13,
	0x3c, 0x21, 0xd1, 0xcc, 0xf2, 0xbd, 0x89, 0x47, 0xf9, 0xf7, 0xcb, 0x06, 0x92, 0xba, 0x73, 0xae,
	0xea, 0x31, 0x0d, 0xfb, 0xb2, 0x8b, 0x7d, 0x7b, 0xc6, 0xea, 0x12, 0xd1, 0x46, 0x81, 0x1b, 0x02,
	0x17, 0xf1, 0x0c, 0xd1, 0x0f, 0x61, 0x1f, 0x07, 0x3c, 0x22, 0xf1, 0x5d, 0xcb, 0x21, 0x93, 0x89,
	0x1d, 0xb8, 0x56, 0x8c, 0xa3, 0x1b, 0x1c, 0x35, 0x8a, 0xdc, 0x7c, 0x4f, 0x18, 0x0c, 0x7c, 0xb7,
	0x2d, 0xd4, 0x23, 0xae, 0x45, 0x87, 0xb0, 0x2d, 0x5d, 0x23, 0xfb, 0x8d, 0x25, 0x32, 0x6d, 0x6c,
	0x72, 0x97, 0x7b, 0x42, 0x61, 0xd8, 0x6f, 0xda, 0x5c, 0xac, 0x5d, 0x43, 0x6d, 0x84, 0xe9, 0x34,
	0x4c, 0x2a, 0xf2, 0x00, 0x2a, 0x97, 0x76, 0x8c, 0xd3, 0xf5, 0x28, 0x33, 0x01, 0xaf, 0xc6, 0x7b,
	0x50, 0x7b, 0x43, 0xa2, 0x6b, 0x2f, 0x90, 0xf5, 0x12, 0xb5, 0xa8, 0x4a, 0x19, 0x37, 0x79, 0x00,
	0x15, 0x8a, 0x27, 0xa1, 0xd0, 0x8b, 0xf2, 0x97, 0x99, 0x80, 0x29, 0x35, 0x07, 0xca, 0xf3, 0xbe,
	0xf8, 0x0c, 0xea, 0x91, 0x1c, 0x5b, 0x0e, 0x71, 0x93, 0xd6, 0x68, 0xa4, 0xb7, 0x38, 0x31, 0x6e,
	0x13, 0x17, 0x1b, 0xb5, 0x28, 0x35, 0x4b, 0x6f, 0x72, 0x2e, 0xbb, 0xc9, 0x1a, 0xd4, 0x3e, 0xc7,
	0xbe, 0x4f, 0x92, 0x15, 0x21, 0x28, 0x04, 0xf6, 0x04, 0xcb, 0xc5, 0xf0, 0xb1, 0xf6, 0x6d, 0xa8,
	0x4b, 0x1b, 0x99, 0x4d, 0x2a, 0x9c, 0x92, 0x0d, 0x57, 0x82, 0xa2, 0x3e, 0x09, 0xe9, 0x4c, 0xfb,
	0x47, 0x0e, 0x60, 0x34, 0x8b, 0x29, 0x9e, 0xb0, 0xfe, 0x46, 0x7b, 0xb0, 0x29, 0xb6, 0x9a, 0x3b,
	0xe4, 0x0d, 0x39, 0x43, 0xef, 0x02, 0x8c, 0x49, 0x44, 0xa6, 0xd4, 0x0b, 0x70, 0xcc, 0x73, 0x2b,
	0x1a, 0x29, 0x89, 0xec, 0xa8, 0x00, 0x3b, 0xd4, 0x23, 0x41, 0x6c, 0x79, 0x01, 0xaf, 0x52, 0x91,
	0x77, 0x54, 0x22, 0xed, 0x06, 0xe8, 0x43, 0xb8, 0x97, 0x36, 0x23, 0x53, 0xd1, 0x23, 0x45, 0x23,
	0xed, 0x3d, 0x98, 0x52, 0xf4, 0x1d, 0xd8, 0xa6, 0x91, 0x7d, 0x75, 0xe5, 0x39, 0x96, 0x7d, 0x63,
	0x7b, 0x3e, 0xdb, 0x5e, 0xd9, 0x1f, 0xaa, 0x54, 0xb4, 0x12, 0x39, 0x4b, 0x7a, 0x1a, 0xfa, 0x5e,
	0x70, 0xcd, 0xdb, 0x21, 0x6f, 0xc8, 0x19, 0x6a, 0x42, 0xd9, 0x25, 0x6f, 0x02, 0xae, 0x29, 0x71,
	0xcd, 0x7c, 0xce, 0x36, 0x5d, 0x58, 0x59, 0x94, 0x50, 0xdb, 0x6f, 0x94, 0xb9, 0xbe, 0x2a, 0x64,
	0x26, 0x13, 0xb1, 0x35, 0x25, 0xe6, 0xd2, 0xa8, 0xc2, 0x8d, 0xea, 0x89, 0x94, 0x9b, 0x69, 0x7f,
	0x54, 0x60, 0x7b, 0x30, 0xa5, 0x97, 0x64, 0x1a, 0xb8, 0x67, 0x11, 0x99, 0x86, 0x5d, 0x8a, 0x27,
	0x48, 0x85, 0x3c, 0xb5, 0xc7, 0xb2, 0xec, 0x6c, 0xc8, 0x76, 0x6c, 0x7e, 0xe8, 0x2b, 0x06, 0x1f,
	0x23, 0x0d, 0xea, 0xd3, 0xc8, 0xb7, 0x28, 0x8e, 0xa9, 0x45, 0xbd, 0x89, 0x38, 0xda, 0x2c, 0x8d,
	0xc8, 0x37, 0x71, 0x4c, 0x4d, 0x6f, 0x82, 0xd1, 0xb7, 0x60, 0x6b, 0x6e, 0xc3, 0x4f, 0x92, 0x2c,
	0x59, 0x4d, 0x1a, 0x75, 0x98, 0x4c, 0xfb, 0x93, 0x02, 0xf5, 0x4c, 0x16, 0x5f, 0x31, 0x83, 0x26,
	0x94, 0x63, 0xec, 0x63, 0x87, 0x62, 0x37, 0x69, 0xec, 0x64, 0x8e, 0x3e, 0x81, 0xa2, 0x47, 0xf1,
	0x24, 0x6e, 0x14, 0x9e, 0xe4, 0x0f, 0xaa, 0xc7, 0x8f, 0xd2, 0x4d, 0x7c, 0x6b, 0xc5, 0x86, 0xb0,
	0xd5, 0x3a, 0x4b, 0xd5, 0xe8, 0x79, 0x31, 0x45, 0x4f, 0x93, 0x48, 0x0a, 0x8f, 0xb4, 0xbf, 0x36,
	0x52, 0x12, 0x65, 0x00, 0xd5, 0x57, 0x76, 0x14, 0xb6, 0x1c, 0x87, 0x4c, 0x03, 0x8a, 0x1e, 0x01,
	0xd8, 0x62, 0x68, 0x79, 0xae, 0x5c, 0x52, 0x45, 0x4a, 0xba, 0x2e, 0xdb, 0x4c, 0xdb, 0x71, 0x70,
	0x1c, 0x5b, 0x94, 0x5c, 0xe3, 0x20, 0x39, 0xc1, 0x42, 0x66, 0x32, 0x91, 0xf6, 0x2f, 0x05, 0x76,
	0x58, 0xc4, 0x57, 0x5e, 0x84, 0xc7, 0x53, 0x3b, 0x72, 0x05, 0x52, 0x30, 0xc4, 0x0a, 0x23, 0xef,
	0xc6, 0xa6, 0xd8, 0xba, 0xc6, 0xb3, 0x04, 0x2b, 0xa5, 0xe8, 0x25, 0x9e, 0xa1, 0x8f, 0x00, 0xf9,
	0xc4, 0xb1, 0x7d, 0xcb, 0x76, 0xdd, 0x88, 0x7d, 0xc2, 0x0b, 0x6f, 0x9e, 0xc9, 0x2f, 0xa8, 0x5c,
	0xd3, 0x12, 0x8a, 0x6e, 0x78, 0xf3, 0x6c, 0xa5, 0xf5, 0xa7, 0xb2, 0xb0, 0xcb, 0xd6, 0x9f, 0xa2,
	0x0f, 0xe0, 0x5e, 0x88, 0x71, 0x64, 0x85, 0xd3, 0x4b, 0xdf, 0x73, 0x78, 0x02, 0x05, 0x01, 0xc4,
	0x4c, 0x3c, 0xe4, 0x52, 0x96, 0xc3, 0x03, 0xa8, 0x38, 0xbe, 0x87, 0xc5, 0xea, 0x8b, 0x62, 0x97,
	0x84, 0xa0, 0xeb, 0x6a, 0x7f, 0x55, 0x60, 0x8f, 0xad, 0xec, 0x0c, 0x07, 0x38, 0xb2, 0xd9, 0x09,
	0x9a, 0x9f, 0xff, 0xef, 0x41, 0x49, 0x16, 0x89, 0x2f, 0xac, 0x9a, 0xbd, 0x6a, 0x52, 0x05, 0x36,
	0x12, 0x3b, 0xd6, 0x35, 0x3e, 0x19, 0xcb, 0xf5, 0xb1, 0x21, 0x7a, 0x0e, 0x9b, 0x12, 0x6c, 0xf3,
	0x3c, 0xc6, 0xe3, 0xe5, 0x18, 0x4b, 0x25, 0x35, 0xa4, 0xb9, 0xf6, 0x12, 0xb6, 0x05, 0xb2, 0x0c,
	0x23, 0xf2, 0x25, 0xc3, 0x7f, 0x3a, 0x8d, 0xd1, 0x43, 0xa8, 0x2c, 0x0e, 0xb4, 0xc2, 0x0f, 0xf4,
	0x42, 0xc0, 0x00, 0x4b, 0x40, 0xb9, 0xcb, 0x33, 0x28, 0x1b, 0xc9, 0x54, 0xfb, 0x1d, 0xd4, 0x86,
	0x76, 0x14, 0xe3, 0x04, 0xff, 0x1a, 0x50, 0x4a, 0xee, 0x2e, 0x09, 0x6d, 0x72, 0xba, 0x7c, 0xfb,
	0xe5, 0x6e, 0xdd, 0x7e, 0x6f, 0x03, 0x73, 0xb4, 0x0b, 0x45, 0x17, 0x5f, 0x4e, 0xc7, 0xf2, 0xee,
	0x12, 0x13, 0xed, 0x0f, 0x0a, 0xd4, 0xe5, 0xe7, 0xbf, 0x31, 0xa0, 0xcf, 0x5e, 0xbd, 0xf3, 0xf4,
	0xd7, 0xdf, 0xf3, 0x3d, 0x68, 0xb6, 0x5f, 0xdb, 0xc1, 0x18, 0x8b, 0x3a, 0x0f, 0x42, 0x8e, 0x96,
	0x49, 0x41, 0x8e, 0x60, 0x47, 0x2e, 0x9b, 0x08, 0x85, 0xf5, 0xeb, 0x98, 0x04, 0xb2, 0x38, 0xdb,
	0x4e, 0xda, 0xe5, 0xa7, 0x31, 0x09, 0xb4, 0x5f, 0xc1, 0x7d, 0xd9, 0x31, 0x32, 0x5e, 0xea, 0x66,
	0x49, 0x5d, 0x93, 0x7c, 0x9c, 0x2d, 0x59, 0x6e, 0x5d, 0xc9, 0xf2, 0xe9, 0x92, 0xbd, 0x80, 0xbd,
	0xe5, 0xf8, 0xb2, 0x74, 0xb7, 0xd9, 0x87, 0xb2, 0x82, 0x7d, 0x68, 0xaf, 0xe0, 0xfe, 0x88, 0x23,
	0x51, 0x02, 0x10, 0xa9, 0xcb, 0x7c, 0xcc, 0xb0, 0xc2, 0x5a, 0xc0, 0x5b, 0x99, 0x0b, 0x4c, 0x7b,
	0xcc, 0xa0, 0x80, 0x48, 0x7b, 0xae, 0x97, 0x50, 0x90, 0xc8, 0x4c, 0x7b, 0xac, 0x7d, 0x17, 0xb6,
	0x2e, 0x04, 0x74, 0x7e, 0x95, 0x88, 0xda, 0xef, 0x61, 0x3f, 0x59, 0x08, 0xeb, 0xf6, 0x6c, 0xb1,
	0x1e, 0x43, 0xd5, 0xf7, 0x1c, 0xcc, 0xba, 0x20, 0x05, 0x1f, 0x52, 0xc4, 0x8e, 0x6e, 0x16, 0xb9,
	0x72, 0x77, 0x21, 0x57, 0xfe, 0x36, 0x72, 0x7d, 0x06, 0x0f, 0x47, 0x98, 0xa6, 0x4e, 0x92, 0x2e,
	0x8e, 0x44, 0x92, 0xc2, 0x23, 0x00, 0x2f, 0xb6, 0x92, 0x63, 0x23, 0x8f, 0x94, 0x17, 0x4b, 0x2b,
	0xed, 0xb7, 0x00, 0x3d, 0x32, 0x96, 0xb4, 0x12, 0x1d, 0x42, 0xd1, 0xc7, 0x37, 0xd8, 0x97, 0xed,
	0xba, 0x9b, 0x6e, 0xd7, 0x1e, 0x19, 0xf7, 0x98, 0xce, 0x10, 0x26, 0xe8, 0xc3, 0xd4, 0x75, 0xb1,
	0x75, 0xbc, 0xb3, 0x64, 0xca, 0x19, 0xaa, 0xb8, 0x43, 0xd6, 0xb7, 0x6c, 0x1d, 0xaa, 0x23, 0x4a,
	0x12, 0x1a, 0xa6, 0xfd, 0x5d, 0x01, 0x64, 0x4e, 0x83, 0x00, 0xfb, 0x19, 0xbe, 0x8a, 0xa0, 0xc0,
	0x61, 0x52, 0xe4, 0xce, 0xc7, 0xac, 0xb0, 0x82, 0x15, 0x5a, 0x21, 0x89, 0x68, 0xc2, 0x38, 0x84,
	0x68, 0x48, 0x22, 0xca, 0x2a, 0x17, 0xd3, 0xc8, 0x73, 0xa8, 0xc5, 0x48, 0x08, 0x96, 0xcd, 0x57,
	0x15, 0x32, 0x83, 0x89, 0xd0, 0x0f, 0xa0, 0x81, 0x03, 0x37, 0x24, 0x1e, 0x2b, 0x7e, 0xe0, 0xe2,
	0x10, 0x07, 0x2e, 0x03, 0xd1, 0xc0, 0x4e, 0xa8, 0xe9, 0x5e, 0xa2, 0xef, 0x2e, 0xd4, 0x7d, 0x9b,
	0xb2, 0x96, 0x8e, 0xa9, 0xed, 0x5c, 0x4b, 0xb0, 0x15, 0x13, 0xed, 0x10, 0xb6, 0x44, 0xf6, 0x77,
	0x13, 0xac, 0x43, 0x0d, 0x6a, 0xe9, 0xe3, 0x8f, 0x36, 0x21, 0x37, 0x78, 0xa9, 0x6e, 0x20, 0x80,
	0xcd, 0xd3, 0x56, 0xb7, 0xa7, 0x77, 0x54, 0xe5, 0xb0, 0x05, 0x95, 0xf9, 0x33, 0x01, 0x55, 0xa1,
	0x34, 0x32, 0x07, 0xc3, 0xa1, 0xde, 0x51, 0x37, 0x50, 0x0d, 0xca, 0x23, 0xb3, 0x65, 0x98, 0xdd,
	0xfe, 0x99, 0xaa, 0x08, 0x55, 0xcb, 0x30, 0xf5, 0x8e, 0x9a, 0x13, 0xaa, 0xc1, 0x70, 0xc8, 0x54,
	0xf9, 0xc3, 0x7f, 0xe6, 0xa0, 0x9a, 0x7a, 0x32, 0xa0, 0x0a, 0x14, 0xf5, 0xf3, 0xa1, 0xf9, 0x85,
	0xba, 0x81, 0xde, 0x81, 0x1d, 0x3e, 0xb4, 0xda, 0x83, 0xfe, 0x69, 0xf7, 0xec, 0xc2, 0x68, 0x99,
	0xdd, 0x41, 0x5f, 0x55, 0x50, 0x03, 0x76, 0x79, 0x38, 0xab, 0x3d, 0x38, 0x3f, 0x6f, 0xf5, 0x3b,
	0xd6, 0x48, 0x37, 0x7e, 0xa6, 0x1b, 0x6a, 0x0e, 0x21, 0xd8, 0x6a, 0x1b, 0x7a, 0xcb, 0xd4, 0xb9,
	0xa8, 0xdb, 0xd6, 0xd5, 0x3c, 0xda, 0x86, 0xba, 0xb0, 0x4e, 0x44, 0x05, 0xb4, 0x0b, 0xea, 0x45,
	0x5f, 0xff, 0xf9, 0x50, 0x6f, 0x9b, 0x7a, 0xc7, 0xd2, 0x0d, 0x63, 0x60, 0xa8, 0x45, 0xb4, 0x03,
	0xf7, 0x5a, 0x3d, 0x43, 0x6f, 0x75, 0xbe, 0xb0, 0x92, 0x6c, 0x37, 0xb3, 0x42, 0xb1, 0xba, 0x12,
	0xda, 0x03, 0xd4, 0xed, 0x8f, 0xcc, 0x56, 0xbf, 0xad, 0x5b, 0xfd, 0x81, 0x69, 0x9d, 0x0e, 0x2e,
	0xfa, 0x1d, 0xb5, 0xcc, 0x12, 0xcb, 0xc8, 0x13, 0x8f, 0xca, 0x0a, 0x8d, 0xf8, 0x00, 0xa0, 0x7d,
	0xb8, 0xcf, 0x13, 0xb0, 0x4e, 0x2e, 0xba, 0xbd, 0x4e, 0xb7, 0x7f, 0x26, 0x97, 0xab, 0x56, 0x99,
	0x93, 0x50, 0x0d, 0x5b, 0xc6, 0x28, 0xa5, 0xa9, 0x2d, 0x34, 0x2c, 0xb3, 0x94, 0xa6, 0x7e, 0x78,
	0x02, 0xe5, 0xe4, 0x18, 0xb0, 0x5a, 0x76, 0xf4, 0x93, 0x8b, 0x33, 0x75, 0x03, 0x95, 0xa1, 0xd0,
	0xed, 0x9f, 0x0e, 0xc4, 0x5e, 0xbc, 0x6a, 0x19, 0x7d, 0x56, 0xfd, 0x1c, 0xaf, 0x36, 0x5f, 0x7d,
	0x9e, 0x0d, 0x4f, 0x5b, 0x66, 0xab, 0xa7, 0x16, 0x0e, 0x3f, 0x82, 0x92, 0x3c, 0x1f, 0xcc, 0xaf,
	0x3d, 0x30, 0x74, 0x75, 0x83, 0xef, 0xa1, 0x2c, 0xa0, 0xc2, 0x9a, 0x40, 0x7e, 0x31, 0x77, 0xfc,
	0x17, 0x05, 0x8a, 0x9c, 0xb5, 0xa3, 0x17, 0x50, 0x1e, 0xd9, 0x33, 0x31, 0xce, 0xdc, 0x23, 0x69,
	0xe2, 0xdf, 0xdc, 0x5f, 0xa1, 0x91, 0xdd, 0xd8, 0x85, 0xad, 0x24, 0xc0, 0x88, 0x46, 0xd8, 0x9e,
	0x7c, 0xad, 0x30, 0x07, 0xca, 0xc7, 0xca, 0xf1, 0xbf, 0x2b, 0x50, 0x60, 0xbd, 0x89, 0x5e, 0x40,
	0x51, 0xbc, 0xdc, 0x32, 0xa1, 0xd2, 0xc7, 0xb7, 0xf9, 0x70, 0xf9, 0xdd, 0x9b, 0x79, 0x29, 0x9f,
	0x2f, 0x5e, 0xcf, 0x8c, 0x0a, 0x32, 0x24, 0x45, 0xef, 0x64, 0x63, 0xcd, 0x01, 0xe2, 0xed, 0xa1,
	0x58, 0x62, 0xe8, 0xe5, 0x82, 0xe6, 0xc6, 0xfc, 0xc5, 0xb2, 0x36, 0xd6, 0x7a, 0xba, 0xca, 0xf2,
	0xe0, 0xc1, 0x06, 0xb0, 0x7d, 0x6e, 0x7b, 0xc1, 0x37, 0x17, 0xb0, 0x03, 0xf5, 0xb3, 0x04, 0xab,
	0xdf, 0x1e, 0x6c, 0x2f, 0xa3, 0x98, 0x3b, 0xf0, 0x28, 0xcf, 0xa1, 0xc8, 0x5f, 0xaf, 0x4b, 0x35,
	0x4f, 0x3d, 0x68, 0x9b, 0xbb, 0xab, 0x78, 0x06, 0xfa, 0x09, 0x14, 0x39, 0x4b, 0xc9, 0x3a, 0xa6,
	0x79, 0x53, 0x76, 0xdf, 0xb3, 0x94, 0xe6, 0x97, 0xb0, 0xb3, 0x82, 0x5f, 0xa0, 0x0f, 0x32, 0x7b,
	0xb2, 0x96, 0x80, 0xdc, 0xd1, 0x06, 0xa7, 0xf2, 0x1f, 0x05, 0x7b, 0xcc, 0x7b, 0x0e, 0xfe, 0xda,
	0xed, 0xf4, 0x1c, 0x0a, 0xac, 0x8c, 0x68, 0x3b, 0x6d, 0xc5, 0x9f, 0xb2, 0x77, 0x38, 0xb6, 0xa0,
	0x64, 0xe0, 0xf8, 0xff, 0x6a, 0x65, 0x76, 0xbe, 0x32, 0x8c, 0x04, 0xbd, 0x97, 0xdd, 0xa0, 0x15,
	0x6c, 0x65, 0xcd, 0x4e, 0xfd, 0x18, 0x4a, 0x92, 0x83, 0xa0, 0x66, 0xda, 0x20, 0x4b, 0x4c, 0xd6,
	0x38, 0x5b, 0x80, 0x6e, 0x33, 0x12, 0xf4, 0x7e, 0xda, 0x76, 0x2d, 0x63, 0x69, 0x6a, 0xcb, 0xf4,
	0x7d, 0xc5, 0xbb, 0xe1, 0x73, 0xd8, 0x3d, 0xcb, 0x50, 0x0e, 0x49, 0xde, 0x57, 0x14, 0xfd, 0xd1,
	0xed, 0x3e, 0x4e, 0x7b, 0x70, 0x12, 0xb7, 0x82, 0xbc, 0xa0, 0x83, 0xa5, 0xd6, 0x5e, 0xcb, 0x6f,
	0xd6, 0xd4, 0xe0, 0x04, 0xaa, 0x0c, 0xa8, 0xef, 0x44, 0x94, 0xbd, 0x25, 0xda, 0x22, 0x2f, 0x4b,
	0x0e, 0x72, 0xff, 0x51, 0xa0, 0x2e, 0xe9, 0x88, 0xec, 0xca, 0x76, 0x82, 0x76, 0xef, 0xa6, 0xdd,
	0x6e, 0x53, 0x96, 0x66, 0xf3, 0xb6, 0x7e, 0x9e, 0xda, 0xf7, 0xd7, 0xb7, 0xe8, 0xdb, 0xdc, 0x9e,
	0xc3, 0xe6, 0xfa, 0x32, 0xdf, 0xf1, 0x3d, 0xfd, 0x4b, 0x8f, 0xfe, 0x8f, 0x6e, 0x27, 0x5b, 0xbf,
	0xa8, 0x1d, 0x3d, 0x5d, 0xa8, 0x2f, 0x37, 0xf9, 0xaf, 0xcf, 0x4f, 0xfe, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xaf, 0x1d, 0x85, 0x16, 0x15, 0x00, 0x00,
}
