// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v2/ezytel/ezytel.proto

package ezytel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request the metadata card of a Telegram public channel
// (name, description preview, avatar, last-post timestamp, unread badge).
type ChannelInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel id, e.g. "durov" — without "@" or "t.me/".
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Last post id the client has already read; used to compute the
	// unread badge (newmsg). 0 means "everything is unread".
	LastRead      int64 `protobuf:"varint,2,opt,name=last_read,json=lastRead,proto3" json:"last_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfoRequest) Reset() {
	*x = ChannelInfoRequest{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfoRequest) ProtoMessage() {}

func (x *ChannelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfoRequest.ProtoReflect.Descriptor instead.
func (*ChannelInfoRequest) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelInfoRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelInfoRequest) GetLastRead() int64 {
	if x != nil {
		return x.LastRead
	}
	return 0
}

type ChannelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Plain-text preview of the most recent post, or "فایل" if it is a media post.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Local cache path of the avatar JPEG, relative to the cache dir
	// returned by GetCacheDir(). Empty if the avatar could not be fetched.
	AvatarPath string `protobuf:"bytes,3,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	// Unix epoch seconds of the most recent post.
	Date int64 `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	// Persian-calendar formatted "MM-DD HH:mm" string for the most recent post.
	DateStr string `protobuf:"bytes,5,opt,name=date_str,json=dateStr,proto3" json:"date_str,omitempty"`
	// Unread badge, e.g. "+12" or "+99" (capped). Empty when caught up.
	Newmsg string `protobuf:"bytes,6,opt,name=newmsg,proto3" json:"newmsg,omitempty"`
	// Last post id observed on the channel page (server-side cookie replacement).
	LastPostId int64 `protobuf:"varint,7,opt,name=last_post_id,json=lastPostId,proto3" json:"last_post_id,omitempty"`
	// True when the channel page was reachable and parsed; false if served
	// from stale cache (newmsg is then forced to "OFF").
	Ok            bool `protobuf:"varint,8,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChannelInfo) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *ChannelInfo) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ChannelInfo) GetDateStr() string {
	if x != nil {
		return x.DateStr
	}
	return ""
}

func (x *ChannelInfo) GetNewmsg() string {
	if x != nil {
		return x.Newmsg
	}
	return ""
}

func (x *ChannelInfo) GetLastPostId() int64 {
	if x != nil {
		return x.LastPostId
	}
	return 0
}

func (x *ChannelInfo) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Request a slab of HTML for the channel timeline.
type ChannelMessagesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// 0 = latest page; otherwise the "before" cursor returned by Telegram
	// (the data-before attribute of messages_more_wrap).
	Before        int64 `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessagesRequest) Reset() {
	*x = ChannelMessagesRequest{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessagesRequest) ProtoMessage() {}

func (x *ChannelMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessagesRequest.ProtoReflect.Descriptor instead.
func (*ChannelMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelMessagesRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMessagesRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

type ChannelMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pre-rendered HTML fragment ready to be injected into .main_block.
	// Image URLs have been rewritten to call ProxyImage; dates have been
	// converted to the Persian calendar.
	Html string `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	// Channel avatar URL embedded in the header (only set when before == 0).
	ChannelAvatar string `protobuf:"bytes,2,opt,name=channel_avatar,json=channelAvatar,proto3" json:"channel_avatar,omitempty"`
	// Last post id seen on the page (mirrors the lastread_<chid> cookie).
	LastPostId    int64 `protobuf:"varint,3,opt,name=last_post_id,json=lastPostId,proto3" json:"last_post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessagesResponse) Reset() {
	*x = ChannelMessagesResponse{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessagesResponse) ProtoMessage() {}

func (x *ChannelMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessagesResponse.ProtoReflect.Descriptor instead.
func (*ChannelMessagesResponse) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelMessagesResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *ChannelMessagesResponse) GetChannelAvatar() string {
	if x != nil {
		return x.ChannelAvatar
	}
	return ""
}

func (x *ChannelMessagesResponse) GetLastPostId() int64 {
	if x != nil {
		return x.LastPostId
	}
	return 0
}

// Fetch a Telegram-hosted image through the translate.goog domain front
// and cache it locally. Mirrors proxy.php?url=<hex>.
type ProxyImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hex-encoded source URL without the "https://" prefix, exactly as the
	// PHP version expected (bin2hex of the host+path).
	HexUrl        string `protobuf:"bytes,1,opt,name=hex_url,json=hexUrl,proto3" json:"hex_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyImageRequest) Reset() {
	*x = ProxyImageRequest{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyImageRequest) ProtoMessage() {}

func (x *ProxyImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyImageRequest.ProtoReflect.Descriptor instead.
func (*ProxyImageRequest) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyImageRequest) GetHexUrl() string {
	if x != nil {
		return x.HexUrl
	}
	return ""
}

type ProxyImageResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Data        []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Local cache filename (md5(url) + ".jpg") for clients that prefer to
	// reload from disk instead of holding the bytes.
	CacheName     string `protobuf:"bytes,3,opt,name=cache_name,json=cacheName,proto3" json:"cache_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyImageResponse) Reset() {
	*x = ProxyImageResponse{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyImageResponse) ProtoMessage() {}

func (x *ProxyImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyImageResponse.ProtoReflect.Descriptor instead.
func (*ProxyImageResponse) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{5}
}

func (x *ProxyImageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProxyImageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProxyImageResponse) GetCacheName() string {
	if x != nil {
		return x.CacheName
	}
	return ""
}

// Parse the operator-supplied newline-separated channel list into the
// normalised ids the other RPCs accept.
type ParseChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           string                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseChannelsRequest) Reset() {
	*x = ParseChannelsRequest{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseChannelsRequest) ProtoMessage() {}

func (x *ParseChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseChannelsRequest.ProtoReflect.Descriptor instead.
func (*ParseChannelsRequest) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{6}
}

func (x *ParseChannelsRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type ParseChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelIds    []string               `protobuf:"bytes,1,rep,name=channel_ids,json=channelIds,proto3" json:"channel_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseChannelsResponse) Reset() {
	*x = ParseChannelsResponse{}
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseChannelsResponse) ProtoMessage() {}

func (x *ParseChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_ezytel_ezytel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseChannelsResponse.ProtoReflect.Descriptor instead.
func (*ParseChannelsResponse) Descriptor() ([]byte, []int) {
	return file_v2_ezytel_ezytel_proto_rawDescGZIP(), []int{7}
}

func (x *ParseChannelsResponse) GetChannelIds() []string {
	if x != nil {
		return x.ChannelIds
	}
	return nil
}

var File_v2_ezytel_ezytel_proto protoreflect.FileDescriptor

const file_v2_ezytel_ezytel_proto_rawDesc = "" +
	"\n" +
	"\x16v2/ezytel/ezytel.proto\x12\x06ezytel\"P\n" +
	"\x12ChannelInfoRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tlast_read\x18\x02 \x01(\x03R\blastRead\"\xdd\x01\n" +
	"\vChannelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vavatar_path\x18\x03 \x01(\tR\n" +
	"avatarPath\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x12\x19\n" +
	"\bdate_str\x18\x05 \x01(\tR\adateStr\x12\x16\n" +
	"\x06newmsg\x18\x06 \x01(\tR\x06newmsg\x12 \n" +
	"\flast_post_id\x18\a \x01(\x03R\n" +
	"lastPostId\x12\x0e\n" +
	"\x02ok\x18\b \x01(\bR\x02ok\"O\n" +
	"\x16ChannelMessagesRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06before\x18\x02 \x01(\x03R\x06before\"v\n" +
	"\x17ChannelMessagesResponse\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12%\n" +
	"\x0echannel_avatar\x18\x02 \x01(\tR\rchannelAvatar\x12 \n" +
	"\flast_post_id\x18\x03 \x01(\x03R\n" +
	"lastPostId\",\n" +
	"\x11ProxyImageRequest\x12\x17\n" +
	"\ahex_url\x18\x01 \x01(\tR\x06hexUrl\"j\n" +
	"\x12ProxyImageResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"cache_name\x18\x03 \x01(\tR\tcacheName\"(\n" +
	"\x14ParseChannelsRequest\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\tR\x03raw\"8\n" +
	"\x15ParseChannelsResponse\x12\x1f\n" +
	"\vchannel_ids\x18\x01 \x03(\tR\n" +
	"channelIdsBK\n" +
	"\x1ecom.hiddify.core.api.v2.ezytelZ)github.com/hiddify/hiddify-core/v2/ezytelb\x06proto3"

var (
	file_v2_ezytel_ezytel_proto_rawDescOnce sync.Once
	file_v2_ezytel_ezytel_proto_rawDescData []byte
)

func file_v2_ezytel_ezytel_proto_rawDescGZIP() []byte {
	file_v2_ezytel_ezytel_proto_rawDescOnce.Do(func() {
		file_v2_ezytel_ezytel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_ezytel_ezytel_proto_rawDesc), len(file_v2_ezytel_ezytel_proto_rawDesc)))
	})
	return file_v2_ezytel_ezytel_proto_rawDescData
}

var file_v2_ezytel_ezytel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v2_ezytel_ezytel_proto_goTypes = []any{
	(*ChannelInfoRequest)(nil),      // 0: ezytel.ChannelInfoRequest
	(*ChannelInfo)(nil),             // 1: ezytel.ChannelInfo
	(*ChannelMessagesRequest)(nil),  // 2: ezytel.ChannelMessagesRequest
	(*ChannelMessagesResponse)(nil), // 3: ezytel.ChannelMessagesResponse
	(*ProxyImageRequest)(nil),       // 4: ezytel.ProxyImageRequest
	(*ProxyImageResponse)(nil),      // 5: ezytel.ProxyImageResponse
	(*ParseChannelsRequest)(nil),    // 6: ezytel.ParseChannelsRequest
	(*ParseChannelsResponse)(nil),   // 7: ezytel.ParseChannelsResponse
}
var file_v2_ezytel_ezytel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_ezytel_ezytel_proto_init() }
func file_v2_ezytel_ezytel_proto_init() {
	if File_v2_ezytel_ezytel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_ezytel_ezytel_proto_rawDesc), len(file_v2_ezytel_ezytel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_ezytel_ezytel_proto_goTypes,
		DependencyIndexes: file_v2_ezytel_ezytel_proto_depIdxs,
		MessageInfos:      file_v2_ezytel_ezytel_proto_msgTypes,
	}.Build()
	File_v2_ezytel_ezytel_proto = out.File
	file_v2_ezytel_ezytel_proto_goTypes = nil
	file_v2_ezytel_ezytel_proto_depIdxs = nil
}
